/* =============================================================================
 *  GHT4 · Agente de Prospecção M&A — DADOS DEMONSTRATIVOS
 * -----------------------------------------------------------------------------
 *  ATENÇÃO: Todas as empresas abaixo são FICTÍCIAS e os números são SIMULADOS.
 *  Os CONTATOS (nome, cargo, e-mail e telefone) também são TOTALMENTE FICTÍCIOS
 *  e não correspondem a nenhuma pessoa real. Nada aqui representa dados reais de
 *  mercado, cadastro, contato ou due diligence. Este arquivo existe apenas para
 *  demonstrar o conceito do agente e deve ser substituído por fontes validadas
 *  após o levantamento de requisitos.
 *
 *  Campos de cada empresa:
 *    oQueFazem         -> explicação mínima da atividade da empresa
 *    receita           -> faturamento anual estimado (R$ milhões)
 *    crescimento       -> crescimento de receita (% a.a.)
 *    margemEbitda      -> margem EBITDA (%)
 *    funcionarios      -> nº de colaboradores
 *    perfil            -> perfil societário
 *    contato           -> { nome, cargo, email, telefone } — FICTÍCIO (demo)
 *    mercadoFragmentado-> setor pulverizado, tese de consolidação (buy-and-build)
 *    rodadaRecente     -> captou investimento nos últimos ~18 meses
 *    mudancaControle   -> sinais de mudança de controle / reorganização societária
 *    expansaoGeografica-> movimento recente de expansão geográfica
 *    descricao         -> contexto societário / situação relevante para M&A
 *    origem            -> natureza do dado (Simulado / Estimativa / Hipótese)
 *    dataAtualizacao   -> "data" fictícia de referência do dado
 *    confianca         -> Alta / Média / Baixa / Incompleto
 * ========================================================================== */

const PERFIS = ['Familiar', 'Founder-led', 'Fundo/PE', 'Capital aberto', 'Multinacional'];

const EMPRESAS_DEMO = [
  // ----------------------------- SAÚDE -----------------------------
  { id: 'sa01', nome: 'Clínica Vitalux', setor: 'Saúde', subsetor: 'Clínicas & Diagnóstico',
    oQueFazem: 'Rede regional de clínicas de diagnóstico por imagem (ressonância, tomografia e ultrassom).',
    cidade: 'Campinas', uf: 'SP', receita: 68, crescimento: 24, margemEbitda: 19, funcionarios: 310,
    perfil: 'Familiar', contato: { nome: 'Helena Prado', cargo: 'Diretora-Geral', email: 'helena.prado@vitalux.com.br', telefone: '+55 (19) 98421-0075' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: false, expansaoGeografica: true,
    origem: 'Simulado', dataAtualizacao: '2026-05-12', confianca: 'Média',
    descricao: 'Rede regional de clínicas de diagnóstico por imagem, controle familiar de 2ª geração.' },
  { id: 'sa02', nome: 'NovaSaúde Gestão', setor: 'Saúde', subsetor: 'Gestão Hospitalar',
    oQueFazem: 'Administra hospitais e prontos-socorros de terceiros (gestão operacional e de suprimentos).',
    cidade: 'Belo Horizonte', uf: 'MG', receita: 420, crescimento: 16, margemEbitda: 27, funcionarios: 1900,
    perfil: 'Fundo/PE', contato: { nome: 'Rafael Menezes', cargo: 'CEO', email: 'rafael.menezes@novasaude.com.br', telefone: '+55 (31) 99160-3382' },
    mercadoFragmentado: false, rodadaRecente: true, mudancaControle: false, expansaoGeografica: true,
    origem: 'Estimativa', dataAtualizacao: '2026-06-03', confianca: 'Alta',
    descricao: 'Plataforma de gestão hospitalar com apoio de fundo de private equity, buscando add-ons.' },
  { id: 'sa03', nome: 'OdontoMais', setor: 'Saúde', subsetor: 'Odontologia',
    oQueFazem: 'Rede de franquias de clínicas odontológicas populares.',
    cidade: 'Curitiba', uf: 'PR', receita: 34, crescimento: 31, margemEbitda: 9, funcionarios: 180,
    perfil: 'Founder-led', contato: { nome: 'Bruno Tavares', cargo: 'Fundador & CEO', email: 'bruno.tavares@odontomais.com.br', telefone: '+55 (41) 98833-1290' },
    mercadoFragmentado: true, rodadaRecente: true, mudancaControle: false, expansaoGeografica: false,
    origem: 'Simulado', dataAtualizacao: '2026-04-21', confianca: 'Baixa',
    descricao: 'Rede de franquias odontológicas em crescimento acelerado, margem ainda pressionada.' },
  { id: 'sa04', nome: 'BioAnálise Labs', setor: 'Saúde', subsetor: 'Laboratórios',
    oQueFazem: 'Laboratório de análises clínicas com coletas próprias e atendimento a convênios.',
    cidade: 'Recife', uf: 'PE', receita: 52, crescimento: 8, margemEbitda: 12, funcionarios: 240,
    perfil: 'Familiar', contato: { nome: 'Sônia Albuquerque', cargo: 'Sócia-Diretora', email: 'sonia.albuquerque@bioanalise.com.br', telefone: '+55 (81) 99204-7751' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: true, expansaoGeografica: false,
    origem: 'Hipótese', dataAtualizacao: '2026-03-10', confianca: 'Incompleto',
    descricao: 'Laboratório tradicional com processo de sucessão familiar em andamento.' },
  { id: 'sa05', nome: 'MedTech Prime', setor: 'Saúde', subsetor: 'HealthTech',
    oQueFazem: 'Software de gestão de sinistros e autorização para operadoras de saúde.',
    cidade: 'São Paulo', uf: 'SP', receita: 88, crescimento: 42, margemEbitda: 15, funcionarios: 260,
    perfil: 'Fundo/PE', contato: { nome: 'Camila Ferraz', cargo: 'CEO', email: 'camila.ferraz@medtechprime.com.br', telefone: '+55 (11) 97455-6610' },
    mercadoFragmentado: false, rodadaRecente: true, mudancaControle: false, expansaoGeografica: true,
    origem: 'Estimativa', dataAtualizacao: '2026-06-28', confianca: 'Média',
    descricao: 'Software de gestão para operadoras de saúde, forte crescimento pós-rodada Série B.' },
  { id: 'sa06', nome: 'Grupo CuidarBem', setor: 'Saúde', subsetor: 'Home Care',
    oQueFazem: 'Atendimento domiciliar de saúde (home care) e internação domiciliar para convênios.',
    cidade: 'Porto Alegre', uf: 'RS', receita: 145, crescimento: 21, margemEbitda: 22, funcionarios: 1200,
    perfil: 'Capital aberto', contato: { nome: 'Eduardo Lima', cargo: 'Diretor de RI', email: 'eduardo.lima@cuidarbem.com.br', telefone: '+55 (51) 99871-2044' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: false, expansaoGeografica: true,
    origem: 'Simulado', dataAtualizacao: '2026-05-30', confianca: 'Alta',
    descricao: 'Operadora de home care listada, ativa em consolidação de players regionais.' },
  { id: 'sa07', nome: 'Farmácias Reviva', setor: 'Saúde', subsetor: 'Varejo Farmacêutico',
    oQueFazem: 'Rede regional de drogarias de bairro com foco em genéricos e conveniência.',
    cidade: 'Goiânia', uf: 'GO', receita: 210, crescimento: 6, margemEbitda: 7, funcionarios: 1400,
    perfil: 'Familiar', contato: { nome: 'Antônio Reis', cargo: 'Presidente', email: 'antonio.reis@farmaciasreviva.com.br', telefone: '+55 (62) 98330-5519' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: true, expansaoGeografica: false,
    origem: 'Simulado', dataAtualizacao: '2026-02-18', confianca: 'Baixa',
    descricao: 'Rede regional de farmácias, margem baixa e disputa societária entre herdeiros.' },
  { id: 'sa08', nome: 'OrtoCenter', setor: 'Saúde', subsetor: 'Clínicas Especializadas',
    oQueFazem: 'Clínica especializada em ortopedia e reabilitação, com centro cirúrgico próprio.',
    cidade: 'Fortaleza', uf: 'CE', receita: 41, crescimento: 27, margemEbitda: 18, funcionarios: 150,
    perfil: 'Founder-led', contato: { nome: 'Dr. Marcos Vieira', cargo: 'Fundador & Diretor Clínico', email: 'marcos.vieira@ortocenter.com.br', telefone: '+55 (85) 99612-8830' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: false, expansaoGeografica: false,
    origem: 'Hipótese', dataAtualizacao: '2026-04-05', confianca: 'Incompleto',
    descricao: 'Clínica ortopédica de referência regional, fundador próximo da aposentadoria.' },

  // --------------------------- TECNOLOGIA ---------------------------
  { id: 'tec01', nome: 'CloudNexo', setor: 'Tecnologia', subsetor: 'SaaS B2B',
    oQueFazem: 'ERP em nuvem para pequenas e médias indústrias (gestão fiscal, estoque e produção).',
    cidade: 'São Paulo', uf: 'SP', receita: 96, crescimento: 48, margemEbitda: 14, funcionarios: 340,
    perfil: 'Fundo/PE', contato: { nome: 'Letícia Cardoso', cargo: 'CEO', email: 'leticia.cardoso@cloudnexo.com.br', telefone: '+55 (11) 98120-4471' },
    mercadoFragmentado: false, rodadaRecente: true, mudancaControle: false, expansaoGeografica: true,
    origem: 'Estimativa', dataAtualizacao: '2026-06-15', confianca: 'Alta',
    descricao: 'ERP vertical em nuvem, crescimento acelerado e apetite por aquisições de nicho.' },
  { id: 'tec02', nome: 'PagaFácil', setor: 'Tecnologia', subsetor: 'Fintech / Pagamentos',
    oQueFazem: 'Adquirente digital: maquininhas e link de pagamento para pequenos comércios.',
    cidade: 'São Paulo', uf: 'SP', receita: 265, crescimento: 55, margemEbitda: 11, funcionarios: 420,
    perfil: 'Fundo/PE', contato: { nome: 'Diego Fontana', cargo: 'CEO', email: 'diego.fontana@pagafacil.com.br', telefone: '+55 (11) 99733-8802' },
    mercadoFragmentado: false, rodadaRecente: true, mudancaControle: false, expansaoGeografica: true,
    origem: 'Estimativa', dataAtualizacao: '2026-07-01', confianca: 'Média',
    descricao: 'Adquirente digital voltada a PMEs, forte tração e recém-capitalizada.' },
  { id: 'tec03', nome: 'DevHouse Studio', setor: 'Tecnologia', subsetor: 'Serviços de Software',
    oQueFazem: 'Fábrica de software sob demanda (nearshoring) para clientes nos EUA e Europa.',
    cidade: 'Florianópolis', uf: 'SC', receita: 44, crescimento: 22, margemEbitda: 17, funcionarios: 280,
    perfil: 'Founder-led', contato: { nome: 'Priscila Nunes', cargo: 'Sócia-Fundadora', email: 'priscila.nunes@devhouse.com.br', telefone: '+55 (48) 98255-9130' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: false, expansaoGeografica: false,
    origem: 'Simulado', dataAtualizacao: '2026-05-08', confianca: 'Média',
    descricao: 'Software house de nearshoring, base de clientes recorrente nos EUA.' },
  { id: 'tec04', nome: 'DataForge Analytics', setor: 'Tecnologia', subsetor: 'Dados & IA',
    oQueFazem: 'Plataforma de analytics e modelos de IA aplicados a previsão de demanda no varejo.',
    cidade: 'Campinas', uf: 'SP', receita: 29, crescimento: 61, margemEbitda: 6, funcionarios: 110,
    perfil: 'Founder-led', contato: { nome: 'Gustavo Rocha', cargo: 'Founder & CTO', email: 'gustavo.rocha@dataforge.com.br', telefone: '+55 (19) 99044-2216' },
    mercadoFragmentado: true, rodadaRecente: true, mudancaControle: false, expansaoGeografica: false,
    origem: 'Hipótese', dataAtualizacao: '2026-06-20', confianca: 'Baixa',
    descricao: 'Startup de analytics e IA aplicada, crescimento explosivo e margem ainda negativa em partes.' },
  { id: 'tec05', nome: 'SegNet Cyber', setor: 'Tecnologia', subsetor: 'Cibersegurança',
    oQueFazem: 'Serviços de segurança da informação: monitoramento (SOC) e resposta a incidentes.',
    cidade: 'Rio de Janeiro', uf: 'RJ', receita: 73, crescimento: 38, margemEbitda: 20, funcionarios: 190,
    perfil: 'Fundo/PE', contato: { nome: 'Fernanda Dias', cargo: 'CEO', email: 'fernanda.dias@segnet.com.br', telefone: '+55 (21) 98670-3345' },
    mercadoFragmentado: false, rodadaRecente: false, mudancaControle: true, expansaoGeografica: true,
    origem: 'Estimativa', dataAtualizacao: '2026-05-25', confianca: 'Média',
    descricao: 'Empresa de segurança da informação; fundo investidor busca liquidez (fim de ciclo).' },
  { id: 'tec06', nome: 'LogiTech Sistemas', setor: 'Tecnologia', subsetor: 'SaaS Logística',
    oQueFazem: 'Software de gestão de transporte e roteirização (TMS) para transportadoras.',
    cidade: 'Curitiba', uf: 'PR', receita: 58, crescimento: 19, margemEbitda: 24, funcionarios: 210,
    perfil: 'Familiar', contato: { nome: 'Ricardo Bianchi', cargo: 'Diretor-Presidente', email: 'ricardo.bianchi@logitechsis.com.br', telefone: '+55 (41) 99527-4108' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: false, expansaoGeografica: false,
    origem: 'Simulado', dataAtualizacao: '2026-04-14', confianca: 'Alta',
    descricao: 'Software de gestão de transportes, cliente fiel e margem saudável.' },
  { id: 'tec07', nome: 'EduPlay Tecnologia', setor: 'Tecnologia', subsetor: 'EdTech',
    oQueFazem: 'Plataforma de educação corporativa (treinamentos online e trilhas de capacitação).',
    cidade: 'Belo Horizonte', uf: 'MG', receita: 28, crescimento: 12, margemEbitda: 8, funcionarios: 160,
    perfil: 'Fundo/PE', contato: { nome: 'Tatiana Moraes', cargo: 'CEO', email: 'tatiana.moraes@eduplay.com.br', telefone: '+55 (31) 98449-7723' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: true, expansaoGeografica: false,
    origem: 'Simulado', dataAtualizacao: '2026-03-22', confianca: 'Baixa',
    descricao: 'Plataforma de educação corporativa; crescimento desacelerou e investidor avalia saída.' },
  { id: 'tec08', nome: 'IndUS Software', setor: 'Tecnologia', subsetor: 'Software Industrial',
    oQueFazem: 'Software de automação e controle de chão de fábrica (MES) para a indústria.',
    cidade: 'Joinville', uf: 'SC', receita: 275, crescimento: 15, margemEbitda: 26, funcionarios: 620,
    perfil: 'Capital aberto', contato: { nome: 'Paulo Hoffmann', cargo: 'Diretor de M&A', email: 'paulo.hoffmann@indussoftware.com.br', telefone: '+55 (47) 99183-6650' },
    mercadoFragmentado: false, rodadaRecente: false, mudancaControle: false, expansaoGeografica: true,
    origem: 'Estimativa', dataAtualizacao: '2026-06-10', confianca: 'Alta',
    descricao: 'Software para manufatura, caixa robusto e estratégia declarada de M&A.' },

  // ----------------------------- VAREJO -----------------------------
  { id: 'var01', nome: 'ModaViva Retail', setor: 'Varejo', subsetor: 'Moda & Vestuário',
    oQueFazem: 'Rede de lojas de moda feminina de médio padrão, com presença em shoppings.',
    cidade: 'São Paulo', uf: 'SP', receita: 240, crescimento: 9, margemEbitda: 10, funcionarios: 2100,
    perfil: 'Familiar', contato: { nome: 'Cláudia Bernardes', cargo: 'Presidente', email: 'claudia.bernardes@modaviva.com.br', telefone: '+55 (11) 98902-1177' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: true, expansaoGeografica: false,
    origem: 'Simulado', dataAtualizacao: '2026-04-30', confianca: 'Média',
    descricao: 'Rede de moda de médio porte; família estuda profissionalização ou venda parcial.' },
  { id: 'var02', nome: 'MercaBom', setor: 'Varejo', subsetor: 'Supermercados',
    oQueFazem: 'Rede regional de supermercados de vizinhança no Nordeste.',
    cidade: 'Salvador', uf: 'BA', receita: 610, crescimento: 7, margemEbitda: 6, funcionarios: 3400,
    perfil: 'Familiar', contato: { nome: 'José Andrade', cargo: 'Diretor-Presidente', email: 'jose.andrade@mercabom.com.br', telefone: '+55 (71) 99345-8820' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: false, expansaoGeografica: true,
    origem: 'Estimativa', dataAtualizacao: '2026-05-19', confianca: 'Média',
    descricao: 'Rede supermercadista regional, margem típica do setor e expansão para o interior.' },
  { id: 'var03', nome: 'PetLar', setor: 'Varejo', subsetor: 'Pet',
    oQueFazem: 'Rede de pet shops com loja física e e-commerce (ração, acessórios e banho/tosa).',
    cidade: 'Campinas', uf: 'SP', receita: 84, crescimento: 33, margemEbitda: 13, funcionarios: 520,
    perfil: 'Founder-led', contato: { nome: 'Marina Castro', cargo: 'Fundadora & CEO', email: 'marina.castro@petlar.com.br', telefone: '+55 (19) 98577-3061' },
    mercadoFragmentado: true, rodadaRecente: true, mudancaControle: false, expansaoGeografica: true,
    origem: 'Simulado', dataAtualizacao: '2026-06-25', confianca: 'Alta',
    descricao: 'Rede pet omnichannel em consolidação, recém-capitalizada para novas lojas.' },
  { id: 'var04', nome: 'CasaPlena Móveis', setor: 'Varejo', subsetor: 'Casa & Decoração',
    oQueFazem: 'Fabricação e varejo de móveis planejados e de decoração para o lar.',
    cidade: 'Bento Gonçalves', uf: 'RS', receita: 155, crescimento: 4, margemEbitda: 9, funcionarios: 900,
    perfil: 'Familiar', contato: { nome: 'Arnaldo Bertotti', cargo: 'Sócio-Diretor', email: 'arnaldo.bertotti@casaplena.com.br', telefone: '+55 (54) 99228-4477' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: true, expansaoGeografica: false,
    origem: 'Hipótese', dataAtualizacao: '2026-02-27', confianca: 'Incompleto',
    descricao: 'Fabricante e varejista de móveis; sucessão indefinida e margem sob pressão.' },
  { id: 'var05', nome: 'NutriMarket', setor: 'Varejo', subsetor: 'Alimentos Saudáveis',
    oQueFazem: 'Rede de lojas de produtos naturais, suplementos e alimentos saudáveis.',
    cidade: 'São Paulo', uf: 'SP', receita: 47, crescimento: 29, margemEbitda: 12, funcionarios: 230,
    perfil: 'Fundo/PE', contato: { nome: 'Isabela Ramos', cargo: 'CEO', email: 'isabela.ramos@nutrimarket.com.br', telefone: '+55 (11) 98066-5540' },
    mercadoFragmentado: true, rodadaRecente: true, mudancaControle: false, expansaoGeografica: true,
    origem: 'Simulado', dataAtualizacao: '2026-06-08', confianca: 'Média',
    descricao: 'Rede de produtos naturais com backing de fundo e plano de expansão nacional.' },
  { id: 'var06', nome: 'EletroTop', setor: 'Varejo', subsetor: 'Eletroeletrônicos',
    oQueFazem: 'Varejo de eletroeletrônicos e eletrodomésticos, físico e online.',
    cidade: 'Manaus', uf: 'AM', receita: 320, crescimento: 5, margemEbitda: 5, funcionarios: 1600,
    perfil: 'Capital aberto', contato: { nome: 'Sérgio Nakamura', cargo: 'Diretor Financeiro', email: 'sergio.nakamura@eletrotop.com.br', telefone: '+55 (92) 99411-7788' },
    mercadoFragmentado: false, rodadaRecente: false, mudancaControle: false, expansaoGeografica: false,
    origem: 'Estimativa', dataAtualizacao: '2026-03-15', confianca: 'Alta',
    descricao: 'Varejista de eletrônicos listada, margem apertada e foco em eficiência.' },
  { id: 'var07', nome: 'BeloAtacado', setor: 'Varejo', subsetor: 'Atacarejo',
    oQueFazem: 'Rede de atacarejo (cash & carry) voltada a pequenos comércios e consumidor final.',
    cidade: 'Goiânia', uf: 'GO', receita: 780, crescimento: 18, margemEbitda: 8, funcionarios: 4200,
    perfil: 'Fundo/PE', contato: { nome: 'Henrique Salles', cargo: 'CEO', email: 'henrique.salles@beloatacado.com.br', telefone: '+55 (62) 99720-1194' },
    mercadoFragmentado: false, rodadaRecente: false, mudancaControle: false, expansaoGeografica: true,
    origem: 'Estimativa', dataAtualizacao: '2026-06-02', confianca: 'Alta',
    descricao: 'Rede de atacarejo com backing de PE, forte apetite consolidador.' },
  { id: 'var08', nome: 'Boutique Aurora', setor: 'Varejo', subsetor: 'Moda de Luxo',
    oQueFazem: 'Marca de moda premium com ateliê próprio e lojas conceito.',
    cidade: 'Rio de Janeiro', uf: 'RJ', receita: 22, crescimento: 14, margemEbitda: 21, funcionarios: 70,
    perfil: 'Familiar', contato: { nome: 'Beatriz Monteiro', cargo: 'Fundadora & Diretora Criativa', email: 'beatriz.monteiro@boutiqueaurora.com.br', telefone: '+55 (21) 98155-6209' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: true, expansaoGeografica: false,
    origem: 'Hipótese', dataAtualizacao: '2026-04-11', confianca: 'Baixa',
    descricao: 'Marca de moda premium, fundadores avaliam venda para grupo maior.' },

  // ----------------------------- ENERGIA -----------------------------
  { id: 'ene01', nome: 'SolarPrime Energia', setor: 'Energia', subsetor: 'Solar Distribuída',
    oQueFazem: 'Integradora de energia solar: projeta e instala sistemas fotovoltaicos.',
    cidade: 'Fortaleza', uf: 'CE', receita: 130, crescimento: 44, margemEbitda: 23, funcionarios: 480,
    perfil: 'Fundo/PE', contato: { nome: 'André Cavalcante', cargo: 'CEO', email: 'andre.cavalcante@solarprime.com.br', telefone: '+55 (85) 99833-4521' },
    mercadoFragmentado: true, rodadaRecente: true, mudancaControle: false, expansaoGeografica: true,
    origem: 'Estimativa', dataAtualizacao: '2026-06-18', confianca: 'Alta',
    descricao: 'Integradora de energia solar em rápido crescimento e consolidando instaladores.' },
  { id: 'ene02', nome: 'VentoNorte', setor: 'Energia', subsetor: 'Eólica',
    oQueFazem: 'Geração de energia eólica: opera parques eólicos e vende energia no mercado.',
    cidade: 'Natal', uf: 'RN', receita: 260, crescimento: 12, margemEbitda: 34, funcionarios: 210,
    perfil: 'Capital aberto', contato: { nome: 'Cristina Alencar', cargo: 'Diretora de RI', email: 'cristina.alencar@ventonorte.com.br', telefone: '+55 (84) 99260-7712' },
    mercadoFragmentado: false, rodadaRecente: false, mudancaControle: false, expansaoGeografica: true,
    origem: 'Estimativa', dataAtualizacao: '2026-05-14', confianca: 'Alta',
    descricao: 'Geradora eólica listada, alta margem e caixa para aquisições de parques.' },
  { id: 'ene03', nome: 'BioGera', setor: 'Energia', subsetor: 'Biogás',
    oQueFazem: 'Produz biogás e biometano a partir de resíduos do agronegócio.',
    cidade: 'Uberlândia', uf: 'MG', receita: 38, crescimento: 36, margemEbitda: 16, funcionarios: 90,
    perfil: 'Founder-led', contato: { nome: 'Thiago Barbosa', cargo: 'Fundador & CEO', email: 'thiago.barbosa@biogera.com.br', telefone: '+55 (34) 99512-8043' },
    mercadoFragmentado: true, rodadaRecente: true, mudancaControle: false, expansaoGeografica: false,
    origem: 'Simulado', dataAtualizacao: '2026-06-22', confianca: 'Média',
    descricao: 'Projeto de biogás a partir de resíduos agro; recém-captou para escalar.' },
  { id: 'ene04', nome: 'HidroSul', setor: 'Energia', subsetor: 'PCH / Hidrelétrica',
    oQueFazem: 'Opera um portfólio de pequenas centrais hidrelétricas (PCHs).',
    cidade: 'Curitiba', uf: 'PR', receita: 175, crescimento: 3, margemEbitda: 41, funcionarios: 140,
    perfil: 'Familiar', contato: { nome: 'Otávio Kruger', cargo: 'Sócio-Presidente', email: 'otavio.kruger@hidrosul.com.br', telefone: '+55 (41) 99388-2260' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: true, expansaoGeografica: false,
    origem: 'Hipótese', dataAtualizacao: '2026-03-05', confianca: 'Incompleto',
    descricao: 'Portfólio de pequenas centrais hidrelétricas; controladores avaliam desinvestimento.' },
  { id: 'ene05', nome: 'ComerLuz', setor: 'Energia', subsetor: 'Comercialização de Energia',
    oQueFazem: 'Comercializadora de energia no mercado livre para empresas.',
    cidade: 'São Paulo', uf: 'SP', receita: 540, crescimento: 20, margemEbitda: 9, funcionarios: 160,
    perfil: 'Fundo/PE', contato: { nome: 'Vanessa Lopes', cargo: 'CEO', email: 'vanessa.lopes@comerluz.com.br', telefone: '+55 (11) 98744-9930' },
    mercadoFragmentado: false, rodadaRecente: false, mudancaControle: false, expansaoGeografica: true,
    origem: 'Estimativa', dataAtualizacao: '2026-06-05', confianca: 'Média',
    descricao: 'Comercializadora no mercado livre de energia, escala e apetite por M&A.' },
  { id: 'ene06', nome: 'EficiênciaJá', setor: 'Energia', subsetor: 'Eficiência Energética',
    oQueFazem: 'ESCO: projetos de eficiência energética (iluminação, climatização, geração).',
    cidade: 'Porto Alegre', uf: 'RS', receita: 26, crescimento: 25, margemEbitda: 7, funcionarios: 85,
    perfil: 'Founder-led', contato: { nome: 'Rodrigo Färber', cargo: 'Fundador & CEO', email: 'rodrigo.farber@eficienciaja.com.br', telefone: '+55 (51) 99603-1178' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: false, expansaoGeografica: false,
    origem: 'Simulado', dataAtualizacao: '2026-04-27', confianca: 'Baixa',
    descricao: 'ESCO de eficiência energética; margem baixa e fundador aberto a sócio estratégico.' },
  { id: 'ene07', nome: 'GNVLog', setor: 'Energia', subsetor: 'Distribuição de Gás',
    oQueFazem: 'Distribui gás natural veicular (GNV) e opera postos de abastecimento.',
    cidade: 'Campinas', uf: 'SP', receita: 295, crescimento: 8, margemEbitda: 18, funcionarios: 640,
    perfil: 'Familiar', contato: { nome: 'Wagner Trindade', cargo: 'Diretor-Presidente', email: 'wagner.trindade@gnvlog.com.br', telefone: '+55 (19) 99255-4402' },
    mercadoFragmentado: true, rodadaRecente: false, mudancaControle: true, expansaoGeografica: false,
    origem: 'Simulado', dataAtualizacao: '2026-02-09', confianca: 'Média',
    descricao: 'Distribuidora de gás veicular; grupo familiar avalia sucessão e venda de controle.' },
  { id: 'ene08', nome: 'StorageX Baterias', setor: 'Energia', subsetor: 'Armazenamento',
    oQueFazem: 'Desenvolve sistemas de armazenamento de energia em baterias (BESS).',
    cidade: 'São José dos Campos', uf: 'SP', receita: 19, crescimento: 70, margemEbitda: -4, funcionarios: 60,
    perfil: 'Fundo/PE', contato: { nome: 'Larissa Pimentel', cargo: 'CEO', email: 'larissa.pimentel@storagex.com.br', telefone: '+55 (12) 99077-3315' },
    mercadoFragmentado: true, rodadaRecente: true, mudancaControle: false, expansaoGeografica: false,
    origem: 'Hipótese', dataAtualizacao: '2026-07-04', confianca: 'Baixa',
    descricao: 'Startup de armazenamento em baterias; crescimento altíssimo, ainda queima caixa.' },
];

/* Exposto globalmente para uso pelo app (sem bundler/import). */
window.EMPRESAS_DEMO = EMPRESAS_DEMO;
window.PERFIS = PERFIS;
