import type { Conversa, EstadoAgente, Tarefa, Usuario } from '../agente/api'
import { IconeRede } from './IconeRede'

export function InicioAgente({ usuario, estado, conversas, aoComecar, aoRetomar, aoRede, aoAjuda, bloqueado }: {
  usuario: Usuario; estado: EstadoAgente; conversas: Conversa[]; aoComecar: (t: Tarefa) => void; aoRetomar: (id: string) => void; aoRede: () => void; aoAjuda: () => void; bloqueado: boolean
}) {
  return <div className="agente-inicio space-y-8">
    <section className="agente-boas-vindas"><div><span className="agente-sobretitulo">Seu próximo movimento</span><h2>Olá, {usuario.nome.split(' ')[0]}.<br />Por onde vamos começar?</h2><p>Encontre empresas, conecte relações e prepare conversas que fazem o trabalho avançar.</p><button className="agente-link" onClick={aoAjuda}><IconeRede nome="ajuda" />Primeira vez? Veja como funciona</button></div><div className="agente-marca-grafica" aria-hidden="true"><span>GHT<span>4</span></span><div className="agente-diagonal" /></div></section>
    <section aria-labelledby="escolha-tarefa"><div className="agente-linha-titulo"><h3 id="escolha-tarefa">O que você quer fazer?</h3><span>Escolha para começar</span></div><div className="agente-acoes-iniciais">{[
      { id: 'buscar_empresas', icone: 'busca', titulo: 'Encontrar empresas', texto: 'Explore o mercado por nome, região e atividade.', acao: 'Iniciar pesquisa', cor: 'laranja' },
      { id: 'mapear_acesso', icone: 'rede', titulo: 'Abrir um caminho', texto: 'Veja quem da GHT4 pode conectar você à liderança.', acao: 'Escolher empresa', cor: 'azul' },
      { id: 'preparar_reuniao', icone: 'agenda', titulo: 'Preparar uma reunião', texto: 'Reúna contexto e perguntas antes da conversa.', acao: 'Preparar roteiro', cor: 'neutra' },
    ].map(a => <button key={a.id} className={`agente-acao-inicial ${a.cor}`} onClick={() => aoComecar(a.id as Tarefa)} disabled={bloqueado || usuario.papel === 'leitura'}><span className="agente-icone-bloco"><IconeRede nome={a.icone as 'busca' | 'rede' | 'agenda'} /></span><h4>{a.titulo}</h4><p>{a.texto}</p><span className="agente-acao-rodape">{a.acao}<IconeRede nome="seta" /></span></button>)}</div>{usuario.papel === 'leitura' && <p className="mt-3 text-sm text-suave">Seu perfil permite consultar. Você pode explorar a rede e as oportunidades pelo menu.</p>}</section>
    <div className="agente-inicio-inferior"><section className="agente-superficie p-6"><div className="agente-linha-titulo"><h3>Continue de onde parou</h3><IconeRede nome="tempo" className="text-suave" /></div>{conversas.length ? <ul className="agente-recentes">{conversas.slice(0, 4).map(c => <li key={c.id}><button onClick={() => aoRetomar(c.id)} disabled={bloqueado}><span className="agente-icone-menor"><IconeRede nome="pasta" /></span><span><strong>{c.titulo}</strong><small>{new Date(c.atualizado_em).toLocaleDateString('pt-BR')} · {c.contexto.frente === 'compra' ? 'Compra' : 'Venda'}</small></span><IconeRede nome="seta" /></button></li>)}</ul> : <div className="agente-vazio-compacto"><IconeRede nome="pasta" /><p>Seu primeiro trabalho começa com uma escolha acima.</p><span>Os resultados ficam salvos aqui para você retomar.</span></div>}</section>
      <section className="agente-convite-rede"><span className="agente-icone-bloco"><IconeRede nome="pessoas" /></span><h3>O acesso começa com quem você conhece.</h3><p>Ajude a construir a rede da casa. Confirme suas relações, uma pessoa por vez.</p><button className="agente-link" onClick={aoRede}>Explorar relacionamentos<IconeRede nome="seta" /></button></section></div>
    {estado.base.disponivel ? <section className="agente-base-real" aria-label="Base de empresas disponível"><div><span className="agente-sobretitulo"><span className="agente-ponto" />Base de empresas</span><h3>{estado.base.subsetor || 'Catálogo de empresas'}</h3><p><strong>{(estado.base.total ?? 0).toLocaleString('pt-BR')} empresas</strong> no recorte inicial · referência {estado.base.referencia?.split('-').reverse().join('/') || 'não informada'}</p></div><details><summary>De onde vêm os dados?</summary><p>{estado.base.fonte || 'Base cadastral configurada'}{estado.base.totalOrigem !== undefined ? ` · ${estado.base.totalOrigem.toLocaleString('pt-BR')} registros na base química de origem` : ''}. A pesquisa começa pelas empresas com enquadramento mais consistente em distribuição e trading. Nos filtros, “Incluir enquadramentos possíveis” amplia a busca para empresas que ainda precisam de revisão. Os dados cadastrais não confirmam faturamento nem interesse em vender; a equipe apura essas informações.</p></details></section> : <p className="agente-nota-base">Base cadastral temporariamente indisponível. Você pode continuar pelos trabalhos salvos.</p>}
  </div>
}
